# Generated by Django 4.2.2 on 2023-06-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0002_members_delete_skillset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
