# Generated by Django 4.2.2 on 2024-01-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0003_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='url',
        ),
    ]
