# Generated by Django 4.2.2 on 2024-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0004_remove_member_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
