# Generated by Django 4.2.2 on 2024-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0006_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(upload_to='media/portfolio/images/'),
        ),
    ]
