# Generated by Django 4.2.2 on 2023-06-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_blogs_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
