# Generated by Django 4.2.2 on 2023-07-15 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 7, 19, 46, 24716, tzinfo=datetime.timezone.utc)),
        ),
    ]
