# Generated by Django 4.2.2 on 2024-01-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 10, 29, 7, 915653, tzinfo=datetime.timezone.utc)),
        ),
    ]
