# Generated by Django 4.2.2 on 2024-02-07 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 7, 17, 45, 130580, tzinfo=datetime.timezone.utc)),
        ),
    ]
